[deps]
Bcrypt = "137488db-d2e6-4fb9-97f3-1e40a263e83c"
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DearDiary = "bcf306fc-d39d-4f25-b732-26abcc96baf2"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JLSO = "9da8a3cd-07a3-59c0-a743-3fdc52c30d11"
JWTs = "d850fbd6-035d-5a70-a269-1ca2e636ac6c"
MLJ = "add582a8-e3ab-11e8-2d5e-e98b27df1bc7"
MLJDecisionTreeInterface = "c6f25543-311c-4c74-83dc-3ea6d1015661"
Memoize = "c03570c3-d221-55d1-a50c-7939bbd78826"
Oxygen = "df9a0d86-3283-4920-82dc-4555fc0d1d8b"
SQLite = "0aa819cd-b072-5ff4-a722-6bc24af294d9"
